### ISSUE TITLE
In app name?

### ISSUE THREAD

**Issue by lil5** [lil5/EnvelopeBudgetMobile#1]
**Options**
* EnvelopeBudget
* EnvelopeBudgetMobile
* Envelope Budget
* Envelope Budget Mobile

@gorgabal what do you think?

**Comment by gorgabal** [comment]
I would call the app itself just EnvelopeBudget . The repository name should signify what platform it is written for. Like 'EnvelopeBudgetMobile' or 'EnvelopeBudgetAndroid'. Is that acceptable? 

In that case, I will call my parts 'EnvelopeBudgetCore', and 'EnvelopeBudgetDesktop'.

**Comment by lil5** [comment]
#76ea9ddfa14d11806cc5522af16c6f0240008f95

**Comment by gorgabal** [comment]
I am not sure if I understand your worry, but I don't have any objection to your proposal either. So it is totally fine.

**Comment by lil5** [comment]
@gorgabal In the file (linked below) on line 1 you see that the android Java file is associated with the package "envelopebudget". Here my scare that adding the core with possibly the same package name might give to issues.

https://github.com/lil5/EnvelopeBudgetMobile/blob/develop/android/app/src/main/java/com/envelopebudget/MainApplication.java

Of course that issue is cleared on the consensus that the core will have a different package name. This is just for clarification.
